<?php
/**
 * EXAMPLE: Refactored ServerC Config to Use CentralControl
 * 
 * This shows how to simplify your ServerC/config.php by delegating
 * all connectivity to CentralControl instead of having scattered functions.
 * 
 * BEFORE: ServerC/config.php had 397 lines with:
 *   - makeAPIRequest() function
 *   - testServerConnection() function
 *   - getServerStatus() function
 *   - areAllServersOnline() function
 *   - Database connection logic
 * 
 * AFTER: Everything is in CentralControl, ServerC/config.php is minimal
 */

// ============================================
// NEW SIMPLIFIED ServerC/config.php
// ============================================

/**
<?php
// ServerC Configuration - User Interface Server
// This file is now MINIMAL - all connectivity is in CentralControl.php

// Load deployment configuration (auto-generated by deploy.php)
require_once __DIR__ . '/deployment_config.php';

// Load central control system
require_once __DIR__ . '/../CentralControl.php';

// Get global central control instance
$cc = getCentralControl();

// Start session
session_start();

// ============================================
// SIMPLE SESSION HELPERS
// ============================================

function isUserLoggedIn() {
    return isset($_SESSION['user_id']);
}

function getCurrentUserId() {
    return $_SESSION['user_id'] ?? null;
}

function getCurrentUsername() {
    return $_SESSION['username'] ?? null;
}

function getCurrentUserEmail() {
    return $_SESSION['user_email'] ?? null;
}

function isCurrentUserAdmin() {
    return isset($_SESSION['is_admin']) && $_SESSION['is_admin'] == 1;
}

function requireUser() {
    if (!isUserLoggedIn()) {
        header('Location: user_login.php');
        exit();
    }
}

function logoutUser() {
    session_destroy();
    header('Location: index.php');
    exit();
}

// ============================================
// DELEGATION TO CENTRALCONTROL (New Way)
// ============================================
// These are convenience wrappers around CentralControl

// Get database connection
function connectDB() {
    global $cc;
    return $cc->db();
}

function connectServerA() {
    global $cc;
    return $cc->db();  // All servers use same database
}

function connectServerB() {
    global $cc;
    return $cc->db();
}

function connectServerC() {
    global $cc;
    return $cc->db();
}

// Old makeAPIRequest function - now delegated to CentralControl
function makeAPIRequest($url, $data = [], $method = 'POST', $options = []) {
    global $cc;
    
    // Determine which server this URL belongs to
    if (strpos($url, 'ServerA') !== false) {
        $api = $cc->api('ServerA');
    } elseif (strpos($url, 'ServerB') !== false) {
        $api = $cc->api('ServerB');
    } else {
        $api = $cc->api('ServerA');  // Default
    }
    
    // Extract endpoint from URL
    if (preg_match('/\/([^\/]+\.php)/', $url, $matches)) {
        $endpoint = $matches[1];
    } else {
        return "error|Invalid endpoint";
    }
    
    // Make request based on method
    if ($method === 'GET') {
        $response = $api->get($endpoint, $data, true);
    } elseif ($method === 'POST') {
        $response = $api->post($endpoint, $data, true);
    } elseif ($method === 'PUT') {
        $response = $api->put($endpoint, $data, true);
    } elseif ($method === 'DELETE') {
        $response = $api->delete($endpoint, $data, true);
    }
    
    return $api->isSuccess() ? json_encode($response) : "error|" . $api->getLastError();
}

// Test server connection - now using CentralControl
function testServerConnection($server_url, $timeout = 5) {
    global $cc;
    
    // Determine which server
    if (strpos($server_url, 'ServerA') !== false) {
        $result = $cc->health()->test('ServerA');
    } elseif (strpos($server_url, 'ServerB') !== false) {
        $result = $cc->health()->test('ServerB');
    } else {
        $result = $cc->health()->test('ServerA');
    }
    
    return [
        'success' => $result['online'],
        'http_code' => $result['http_code'],
        'error' => $result['error'],
        'response_time' => $result['response_time'],
        'response' => $result['response']
    ];
}

// Get server status - now using CentralControl
function getServerStatus($server_url, $server_name, $timeout = 5) {
    global $cc;
    
    // Map server name to identifier
    $server_id = ($server_name === 'Server A') ? 'ServerA' : 
                 ($server_name === 'Server B') ? 'ServerB' : 'ServerC';
    
    $health = $cc->health()->test($server_id);
    
    return [
        'name' => $server_name,
        'url' => $server_url,
        'online' => $health['online'],
        'response_time' => $health['response_time'],
        'http_code' => $health['http_code'],
        'error' => $health['error'],
        'response' => $health['response'] ?? ''
    ];
}

// Check if all servers are online - now using CentralControl
function areAllServersOnline() {
    global $cc;
    return $cc->health()->allOnline();
}

// ============================================
// UPLOAD PATH HELPERS
// ============================================

define('UPLOADS_PATH', __DIR__ . '/../ServerB/uploads/');
define('UPLOADS_URL', '../ServerB/uploads/');
define('UPLOADS_HTTP_URL', UPLOADS_BASE_URL);

function getImageUrl($filename) {
    if (empty($filename)) return '';
    $localPath = UPLOADS_PATH . $filename;
    if (file_exists($localPath)) {
        return UPLOADS_URL . $filename;
    }
    return UPLOADS_HTTP_URL . $filename;
}

function getImagePath($filename) {
    if (empty($filename)) return '';
    return UPLOADS_PATH . $filename;
}

function imageExists($filename) {
    if (empty($filename)) return false;
    return file_exists(getImagePath($filename));
}

?>
 */

// ============================================
// COMPARISON: BEFORE vs AFTER
// ============================================

/**
 * BEFORE (Old Way - 397 lines in ServerC/config.php):
 * 
 * - makeAPIRequest() function with retry logic (100+ lines)
 * - testServerConnection() function
 * - getServerStatus() function
 * - areAllServersOnline() function
 * - Database connection code
 * - Manual cURL handling
 * - Manual error handling
 * - Manual timeout management
 * - Duplicated across multiple files
 * 
 * AFTER (New Way - 80 lines, delegates to CentralControl):
 * 
 * - Simple wrapper functions that delegate to $cc object
 * - All connectivity logic in ONE place: CentralControl.php
 * - Database access: $cc->db()
 * - API requests: $cc->api('ServerA')->post(...)
 * - Health checks: $cc->health()->test(...)
 * - System status: $cc->status()->getAll()
 * - Consistent error handling everywhere
 * - Easy to test: central_control_test.php
 * - Easy to maintain: One file to update
 */

// ============================================
// USAGE IN YOUR FILES
// ============================================

/**
 * In any file that needs connectivity:
 * 
 * Option 1 (Direct - Recommended for new code):
 *   $cc = getCentralControl();
 *   $db = $cc->db();
 *   $api = $cc->api('ServerA');
 *   $health = $cc->health()->testAll();
 * 
 * Option 2 (Via Wrapper Functions - For backwards compatibility):
 *   $db = connectDB();
 *   $response = makeAPIRequest(SERVERA_URL . '/register_user.php', $data);
 *   $all_online = areAllServersOnline();
 * 
 * Option 3 (Global Shortcuts):
 *   $db = cc_db();
 *   $api = cc_api('ServerB');
 *   $health = cc_health()->testAll();
 */

// ============================================
// MIGRATION CHECKLIST
// ============================================

/**
 * □ Include CentralControl.php in config files
 * □ Remove makeAPIRequest() functions from configs
 * □ Remove testServerConnection() functions from configs
 * □ Remove custom database connection code
 * □ Update calls to use $cc->db() and $cc->api()
 * □ Update health checks to use $cc->health()->test()
 * □ Test everything at: localhost/Lostnfound/central_control_test.php
 * □ View logs at: temp directory (see $cc->getLogFile())
 * □ Deploy with deploy.php as before
 */

// ============================================
// BENEFITS
// ============================================

/**
 * ✓ Single Point of Control: All connectivity in CentralControl.php
 * ✓ Consistency: Same connection handling everywhere
 * ✓ Reliability: Retry logic, error handling, timeouts built-in
 * ✓ Testing: central_control_test.php tests all connectivity
 * ✓ Maintainability: Change once, affects all servers
 * ✓ Debugging: Central logging system
 * ✓ Performance: Connection pooling, efficient queries
 * ✓ Security: Parameterized queries, SSL options
 * ✓ Flexibility: Works with local, split, production, ngrok modes
 * ✓ Scalability: Easy to add new servers or connections
 */

?>
