<?php
/**
 * QUICK START GUIDE - Central Control System Integration
 * 
 * This is a quick reference for integrating CentralControl into your existing code
 */

// ============================================
// STEP 1: INCLUDE CENTRAL CONTROL
// ============================================

require_once 'CentralControl.php';
$cc = getCentralControl();

// ============================================
// STEP 2: DATABASE OPERATIONS
// ============================================

// Get connection
$db = $cc->db();

// Query with parameters (safe)
$users = $db->getRows("SELECT * FROM users WHERE role = ?", ['admin']);

// Get one row
$user = $db->getRow("SELECT * FROM users WHERE id = ?", [$user_id]);

// Insert
$id = $db->insert('users', ['email' => $email, 'username' => $username]);

// Update
$db->update('users', ['active' => 1], 'id = ?', [$user_id]);

// Delete
$db->delete('users', 'id = ?', [$user_id]);

// Count
$count = $db->count('users');

// ============================================
// STEP 3: API CALLS
// ============================================

// Get API client for ServerA
$api = $cc->api('ServerA');

// POST request
$result = $api->post('register_user.php', ['email' => $email, 'password' => $password], true);

// GET request
$items = $api->get('get_items.php', ['category' => 'lost'], true);

// PUT request
$api->put('update_item.php', ['id' => $id, 'status' => 'found'], true);

// DELETE request
$api->delete('delete_item.php', ['id' => $id], true);

// Check success
if ($api->isSuccess()) {
    echo "Success!";
} else {
    echo "Error: " . $api->getLastError();
}

// ============================================
// STEP 4: HEALTH CHECKS
// ============================================

// Test one server
$health = $cc->health()->test('ServerA');
if ($health['online']) {
    echo "ServerA is online";
}

// Test all servers
$all = $cc->health()->testAll();
foreach ($all as $server => $status) {
    echo "$server: " . ($status['online'] ? 'ONLINE' : 'OFFLINE');
}

// Quick check
if ($cc->health()->allOnline()) {
    echo "All systems operational";
}

// ============================================
// STEP 5: SYSTEM STATUS
// ============================================

// Get complete status
$status = $cc->status()->getAll();

// Check health
if ($status['overall_health'] === 'healthy') {
    echo "System is healthy";
}

// Access deployment info
echo "Mode: " . $status['deployment']['mode'];
echo "Database: " . $status['deployment']['db_host'];

// ============================================
// ACCESSING FROM ANY FILE
// ============================================

/**
 * In any PHP file, you can access central control:
 * 
 * // At top of file
 * require_once __DIR__ . '/../CentralControl.php';
 * $cc = getCentralControl();
 * 
 * // Then use anywhere
 * $db = $cc->db();
 * $api = $cc->api('ServerA');
 * 
 * Or use global shortcuts:
 * 
 * $db = cc_db();
 * $api = cc_api('ServerA');
 * $health = cc_health();
 * $status = cc_status();
 */

// ============================================
// TESTING EVERYTHING
// ============================================

/**
 * Visit this URL to test all connectivity:
 * 
 *   http://localhost/Lostnfound/central_control_test.php
 * 
 * This will test:
 * ✓ Deployment configuration
 * ✓ Server health (all 3 servers)
 * ✓ Database connectivity
 * ✓ API communication
 * ✓ System status
 * 
 * Or from CLI:
 * 
 *   php central_control_test.php
 */

// ============================================
// CONFIGURATION
// ============================================

/**
 * All configuration is in deployment_config.php in each server folder
 * 
 * Generated by deploy.php - manually edit deploy.php to change:
 * 
 * // In deploy.php
 * $deployment_configs = [
 *     'local' => [
 *         'servera_ip' => 'localhost',
 *         'serverb_ip' => 'localhost',
 *         'serverc_ip' => 'localhost',
 *         // ...
 *     ],
 *     'production' => [
 *         'servera_ip' => '192.168.x.x',
 *         // ...
 *     ]
 * ];
 * 
 * Then run: php deploy.php
 * 
 * This updates all server configs automatically
 */

// ============================================
// LOGGING & DEBUGGING
// ============================================

// Enable debug mode
$cc = new CentralControl(true);

// Log messages
$cc->log("User registration started");
$cc->log("Error occurred", 'error');
$cc->log("Warning: Slow response", 'warning');

// Get log file path
$log_file = $cc->getLogFile();
echo "Logs at: $log_file";

// ============================================
// PRACTICAL EXAMPLES
// ============================================

// Example 1: Register user
function registerNewUser($username, $email, $password) {
    $cc = getCentralControl();
    
    // Validate email not exists
    $db = $cc->db();
    $existing = $db->getRow("SELECT id FROM users WHERE email = ?", [$email]);
    if ($existing) {
        return ['error' => 'Email already registered'];
    }
    
    // Register via ServerA API
    $api = $cc->api('ServerA');
    $response = $api->post('register_user.php', [
        'username' => $username,
        'email' => $email,
        'password' => $password
    ], true);
    
    return $api->isSuccess() 
        ? $response 
        : ['error' => $api->getLastError()];
}

// Example 2: Create lost item
function createLostItem($title, $description, $category) {
    $cc = getCentralControl();
    $db = $cc->db();
    
    $item_id = $db->insert('items', [
        'title' => $title,
        'description' => $description,
        'category' => $category,
        'type' => 'lost',
        'created_at' => date('Y-m-d H:i:s')
    ]);
    
    return $item_id 
        ? ['success' => true, 'id' => $item_id]
        : ['error' => 'Failed to create item'];
}

// Example 3: Check system health for dashboard
function getDashboardHealth() {
    $cc = getCentralControl();
    
    $health = $cc->health()->getSummary();
    $status = $cc->status()->getAll();
    
    return [
        'status' => $status['overall_health'],
        'servers_online' => $health['online_count'] . '/' . $health['total_servers'],
        'database' => $status['deployment']['db_host'],
        'mode' => $status['deployment']['mode']
    ];
}

// ============================================
// BACKWARDS COMPATIBILITY
// ============================================

/**
 * If you have existing code using old functions, you can still use them:
 * 
 * Old code:
 *   $conn = mysqli_connect($host, $user, $pass, $db);
 *   $result = makeAPIRequest(SERVERA_URL . '/register.php', $data);
 * 
 * Still works if you wrap in config.php:
 *   function makeAPIRequest($url, $data, ...) {
 *       $cc = getCentralControl();
 *       // delegate to $cc->api()
 *   }
 * 
 * But new code should use:
 *   $cc = getCentralControl();
 *   $api = $cc->api('ServerA');
 *   $api->post('register.php', $data);
 */

// ============================================
// FEATURES
// ============================================

/**
 * CentralControl Features:
 * 
 * Database:
 * □ Prepared statements (secure)
 * □ Query execution and result retrieval
 * □ Insert, Update, Delete operations
 * □ Count, exists checks
 * □ Automatic charset handling
 * □ Connection pooling
 * 
 * API:
 * □ GET, POST, PUT, DELETE methods
 * □ Automatic retry with exponential backoff
 * □ JSON response parsing
 * □ Error handling and logging
 * □ Timeout management
 * □ SSL verification options
 * 
 * Health:
 * □ Test individual servers
 * □ Test all servers
 * □ Response time measurement
 * □ Online/offline status
 * □ Health summary
 * 
 * Status:
 * □ Overall system health
 * □ All server statuses
 * □ Deployment information
 * □ Timestamp tracking
 * 
 * Configuration:
 * □ Deployment mode detection
 * □ Server IP management
 * □ Database host/name/user/pass
 * □ API URLs
 * □ Protocol (HTTP/HTTPS)
 * □ Production vs Development modes
 */

// ============================================
// TROUBLESHOOTING
// ============================================

/**
 * Problem: Database connection fails
 * Solution: 
 *   $db = $cc->db();
 *   if ($db === null) {
 *       echo "Database not connected";
 *       echo "Check deployment_config.php";
 *   }
 * 
 * Problem: API requests fail
 * Solution:
 *   $api = $cc->api('ServerA');
 *   $api->get('health.php', [], true);
 *   echo $api->getLastError();
 *   echo $api->getLastHttpCode();
 * 
 * Problem: Servers appear offline
 * Solution:
 *   $health = $cc->health()->test('ServerA');
 *   echo $health['error'];
 *   // Check server is actually running
 *   // Check deployment mode matches
 * 
 * Check logs:
 *   $log_file = $cc->getLogFile();
 *   tail -f $log_file
 */

// ============================================
// FILES IN THIS SYSTEM
// ============================================

/**
 * CentralControl.php
 *   - Main control system with all classes
 *   - Database management
 *   - API communication
 *   - Health monitoring
 *   - Status tracking
 * 
 * central_control_test.php
 *   - Testing interface
 *   - View at: localhost/Lostnfound/central_control_test.php
 *   - Tests all connectivity
 * 
 * CENTRAL_CONTROL_USAGE.php
 *   - Detailed usage examples
 *   - Shows all methods
 *   - Migration guide
 * 
 * EXAMPLE_REFACTORED_SERVERC.php
 *   - Shows how to refactor ServerC/config.php
 *   - Minimal wrapper functions
 *   - Delegates to CentralControl
 * 
 * deploy.php
 *   - Deployment configuration manager
 *   - Works as before
 *   - Updates deployment_config.php in each server
 */

?>
