<?php
/**
 * Auto-generated Deployment Configuration for ServerA
 * Generated on: 2025-10-31 06:40:57
 * Deployment Mode: local - Local Development (All on localhost)
 * 
 * DO NOT EDIT THIS FILE MANUALLY - it will be overwritten
 * Edit deploy.php instead and run it to regenerate
 */

// ============================================
// DEPLOYMENT MODE AND SERVER INFO
// ============================================
define('DEPLOYMENT_MODE', 'local');
define('DEPLOYMENT_NAME', 'Local Development (All on localhost)');
define('CURRENT_SERVER', 'ServerA');

// ============================================
// SERVER IP ADDRESSES
// ============================================
define('SERVERA_IP', 'localhost');
define('SERVERB_IP', 'localhost');
define('SERVERC_IP', 'localhost');

// ============================================
// DATABASE CONFIGURATION
// ============================================
define('DB_HOST', 'localhost');  // Connect to ServerB
define('DB_NAME', 'lostfound_db');
define('DB_USER', 'root');
define('DB_PASS', '');

// ============================================
// API AND SERVICE URLS
// ============================================
define('SERVERA_API_URL', 'http://localhost/Lostnfound/ServerA/api');
define('SERVERB_API_URL', 'http://localhost/Lostnfound/ServerB/api');
define('SERVERC_API_URL', 'http://localhost/Lostnfound/ServerC/api');

// Upload URLs (ServerB hosts uploads)
define('UPLOADS_BASE_URL', 'http://localhost/Lostnfound/ServerB/uploads/');

// Health check URLs
define('SERVERA_HEALTH_URL', 'http://localhost/Lostnfound/ServerA/api/health.php');
define('SERVERB_HEALTH_URL', 'http://localhost/Lostnfound/ServerB/api/health.php');
define('SERVERC_HEALTH_URL', 'http://localhost/Lostnfound/ServerC/health.php');

// ============================================
// SERVER ROLE DEFINITIONS
// ============================================
define('SERVER_ROLES', [
    'ServerA' => 'Authentication Server',
    'ServerB' => 'Database & File Server', 
    'ServerC' => 'User Interface Server'
]);

// ============================================
// DEPLOYMENT VALIDATION
// ============================================
function validateDeploymentConfig() {
    $errors = [];
    
    // Check required constants
    $required = ['SERVERA_IP', 'SERVERB_IP', 'SERVERC_IP', 'DB_HOST', 'DB_NAME'];
    foreach ($required as $constant) {
        if (!defined($constant)) {
            $errors[] = "Missing required constant: $constant";
        }
    }
    
    // Validate IP addresses
    $ips = [SERVERA_IP, SERVERB_IP, SERVERC_IP];
    foreach ($ips as $ip) {
        if ($ip !== 'localhost' && !filter_var($ip, FILTER_VALIDATE_IP)) {
            $errors[] = "Invalid IP address: $ip";
        }
    }
    
    return $errors;
}

// ============================================
// HELPER FUNCTIONS
// ============================================
function getCurrentServerRole() {
    return SERVER_ROLES[CURRENT_SERVER] ?? 'Unknown Server';
}

function getDeploymentInfo() {
    return [
        'mode' => DEPLOYMENT_MODE,
        'name' => DEPLOYMENT_NAME,
        'server' => CURRENT_SERVER,
        'server_role' => getCurrentServerRole(),
        'servera_ip' => SERVERA_IP,
        'serverb_ip' => SERVERB_IP,
        'serverc_ip' => SERVERC_IP,
        'database_host' => DB_HOST,
        'validation_errors' => validateDeploymentConfig(),
        'generated_at' => '2025-10-31 06:40:57'
    ];
}

function isLocalDeployment() {
    return DEPLOYMENT_MODE === 'local';
}

function isProductionDeployment() {
    return DEPLOYMENT_MODE === 'production';
}

// Auto-validate configuration
$validation_errors = validateDeploymentConfig();
if (!empty($validation_errors)) {
    error_log("Deployment Configuration Errors for ServerA: " . implode(', ', $validation_errors));
}

// Log deployment info
error_log("ServerA loaded deployment config: " . DEPLOYMENT_MODE . " mode");
?>