<?php
/**
 * Auto-generated Deployment Configuration for ServerA
 * Generated on: 2025-10-31 09:37:16
 * Deployment Mode: ngrok - Ngrok Tunnel Deployment
 * 
 * DO NOT EDIT THIS FILE MANUALLY - it will be overwritten
 * Edit deploy.php instead and run it to regenerate
 */

// ============================================
// DEPLOYMENT MODE AND SERVER INFO
// ============================================
define('DEPLOYMENT_MODE', 'staging');
define('DEPLOYMENT_NAME', 'Staging Deployment');
define('CURRENT_SERVER', 'ServerA');

// ============================================
// SERVER IP ADDRESSES
// ============================================
define('SERVERA_IP', '172.24.194.6');
define('SERVERB_IP', '172.24.194.6');
define('SERVERC_IP', '172.24.14.184');

// ============================================
// DATABASE CONFIGURATION
// ============================================
define('DB_HOST', '172.24.194.6');  // Remote database on ServerB
define('DB_NAME', 'lostfound_db');
define('DB_USER', 'root');
define('DB_PASS', 'Isaac@1234');

// ============================================
// API AND SERVICE URLS
// ============================================
define('SERVERA_API_URL', 'http://172.24.194.6/Lostnfound/ServerA/api');
define('SERVERB_API_URL', 'http://172.24.194.6/Lostnfound/ServerB/api');
define('SERVERC_API_URL', 'http://172.24.14.184/Lostnfound/ServerC/api');

// Upload URLs (ServerB hosts uploads)
define('UPLOADS_BASE_URL', 'http://172.24.194.6/Lostnfound/ServerB/uploads/');

// Health check URLs
define('SERVERA_HEALTH_URL', 'http://172.24.194.6/Lostnfound/ServerA/api/health.php');
define('SERVERB_HEALTH_URL', 'http://172.24.194.6/Lostnfound/ServerB/api/health.php');
define('SERVERC_HEALTH_URL', 'http://172.24.14.184/Lostnfound/ServerC/health.php');

// ============================================
// SERVER ROLE DEFINITIONS
// ============================================
define('SERVER_ROLES', [
    'ServerA' => 'Authentication Server',
    'ServerB' => 'Database & File Server', 
    'ServerC' => 'User Interface Server'
]);

// ============================================
// DEPLOYMENT VALIDATION
// ============================================
if (!function_exists('validateDeploymentConfig')) {
function validateDeploymentConfig() {
    $errors = [];
    
    // Check required constants
    $required = ['SERVERA_IP', 'SERVERB_IP', 'SERVERC_IP', 'DB_HOST', 'DB_NAME'];
    foreach ($required as $constant) {
        if (!defined($constant)) {
            $errors[] = "Missing required constant: $constant";
        }
    }
    
    // Validate IP addresses and hostnames
    $hosts = [SERVERA_IP, SERVERB_IP, SERVERC_IP];
    foreach ($hosts as $host) {
        if ($host !== 'localhost' && !filter_var($host, FILTER_VALIDATE_IP) && !filter_var($host, FILTER_VALIDATE_DOMAIN)) {
            $errors[] = "Invalid IP address or hostname: $host";
        }
    }
    
    return $errors;
}
}

// ============================================
// HELPER FUNCTIONS
// ============================================
if (!function_exists('getCurrentServerRole')) {
function getCurrentServerRole() {
    return SERVER_ROLES[CURRENT_SERVER] ?? 'Unknown Server';
}
}

if (!function_exists('getDeploymentInfo')) {
function getDeploymentInfo() {
    return [
        'mode' => DEPLOYMENT_MODE,
        'name' => DEPLOYMENT_NAME,
        'server' => CURRENT_SERVER,
        'server_role' => getCurrentServerRole(),
        'servera_ip' => SERVERA_IP,
        'serverb_ip' => SERVERB_IP,
        'serverc_ip' => SERVERC_IP,
        'database_host' => DB_HOST,
        'validation_errors' => validateDeploymentConfig(),
        'generated_at' => '2025-10-31 09:37:16'
    ];
}
}

if (!function_exists('isLocalDeployment')) {
function isLocalDeployment() {
    return DEPLOYMENT_MODE === 'local';
}
}

if (!function_exists('isProductionDeployment')) {
function isProductionDeployment() {
    return DEPLOYMENT_MODE === 'production';
}
}

// Auto-validate configuration
$validation_errors = validateDeploymentConfig();
if (!empty($validation_errors)) {
    error_log("Deployment Configuration Errors for ServerA: " . implode(', ', $validation_errors));
}

// Log deployment info
error_log("ServerA loaded deployment config: " . DEPLOYMENT_MODE . " mode");
?>