<?php
/**
 * Auto-generated Deployment Configuration for UserServer
 * Generated on: 2025-10-31 09:37:16
 * Deployment Mode: ngrok - Ngrok Tunnel Deployment
 * 
 * DO NOT EDIT THIS FILE MANUALLY - it will be overwritten
 * Edit deploy.php instead and run it to regenerate
 */

// ============================================
// DEPLOYMENT MODE AND SERVER INFO
// ============================================
define('DEPLOYMENT_MODE', 'staging');
define('DEPLOYMENT_NAME', 'Staging Deployment');
define('CURRENT_SERVER', 'UserServer');

// ============================================
// SERVER IP ADDRESSES
// ============================================
define('ITEMSSERVER_IP', '172.24.194.6');
define('USERSERVER_IP', '172.24.194.6');
define('FRONTEND_IP', '172.24.14.184');

// ============================================
// DATABASE CONFIGURATION
// ============================================
define('DB_HOST', '172.24.194.6');  // Local database on this server
define('DB_NAME', 'lostfound_db');
define('DB_USER', 'root');
define('DB_PASS', 'Isaac@1234');

// ============================================
// API AND SERVICE URLS
// ============================================
define('ITEMSSERVER_API_URL', 'http://172.24.194.6/Lostnfound/ItemsServer/api');
define('USERSERVER_API_URL', 'http://172.24.194.6/Lostnfound/UserServer/api');
define('FRONTEND_API_URL', 'http://172.24.14.184/Lostnfound/Frontend/api');

// Upload URLs (ItemsServer hosts uploads - Items Service)
define('UPLOADS_BASE_URL', 'http://172.24.194.6/Lostnfound/ItemsServer/uploads/');

// Health check URLs
define('ITEMSSERVER_HEALTH_URL', 'http://172.24.194.6/Lostnfound/ItemsServer/api/health.php');
define('USERSERVER_HEALTH_URL', 'http://172.24.194.6/Lostnfound/UserServer/api/health.php');
define('FRONTEND_HEALTH_URL', 'http://172.24.14.184/Lostnfound/Frontend/health.php');

// ============================================
// SERVER ROLE DEFINITIONS
// ============================================
define('SERVER_ROLES', [
    'ItemsServer' => 'Item Logic Server (with uploads)',
    'UserServer' => 'User Logic & Database Server', 
    'Frontend' => 'User Interface Client'
]);

// ============================================
// DEPLOYMENT VALIDATION
// ============================================
if (!function_exists('validateDeploymentConfig')) {
function validateDeploymentConfig() {
    $errors = [];
    
    // Check required constants
    $required = ['ITEMSSERVER_IP', 'USERSERVER_IP', 'FRONTEND_IP', 'DB_HOST', 'DB_NAME'];
    foreach ($required as $constant) {
        if (!defined($constant)) {
            $errors[] = "Missing required constant: $constant";
        }
    }
    
    // Validate IP addresses and hostnames
    $hosts = [ITEMSSERVER_IP, USERSERVER_IP, FRONTEND_IP];
    foreach ($hosts as $host) {
        if ($host !== 'localhost' && !filter_var($host, FILTER_VALIDATE_IP) && !filter_var($host, FILTER_VALIDATE_DOMAIN)) {
            $errors[] = "Invalid IP address or hostname: $host";
        }
    }
    
    return $errors;
}
}

// ============================================
// HELPER FUNCTIONS
// ============================================
if (!function_exists('getCurrentServerRole')) {
function getCurrentServerRole() {
    return SERVER_ROLES[CURRENT_SERVER] ?? 'Unknown Server';
}
}

if (!function_exists('getDeploymentInfo')) {
function getDeploymentInfo() {
    return [
        'mode' => DEPLOYMENT_MODE,
        'name' => DEPLOYMENT_NAME,
        'server' => CURRENT_SERVER,
        'server_role' => getCurrentServerRole(),
        'itemsserver_ip' => ITEMSSERVER_IP,
        'userserver_ip' => USERSERVER_IP,
        'frontend_ip' => FRONTEND_IP,
        'database_host' => DB_HOST,
        'validation_errors' => validateDeploymentConfig(),
        'generated_at' => '2025-10-31 09:37:16'
    ];
}
}

if (!function_exists('isLocalDeployment')) {
function isLocalDeployment() {
    return DEPLOYMENT_MODE === 'local';
}
}

if (!function_exists('isProductionDeployment')) {
function isProductionDeployment() {
    return DEPLOYMENT_MODE === 'production';
}
}

// Auto-validate configuration
$validation_errors = validateDeploymentConfig();
if (!empty($validation_errors)) {
    error_log("Deployment Configuration Errors for UserServer: " . implode(', ', $validation_errors));
}

// Log deployment info
error_log("UserServer loaded deployment config: " . DEPLOYMENT_MODE . " mode");
?>